### ISSUE TITLE
Upgrade to be a Polymer 1.9-2.0 hybrid component

### ISSUE THREAD

**Issue by warpech** [display-interactive/pikaday-decorator#2]
Any plans to upgrade this neat component to be a hybrid element compatible with Polymer 1.9 and 2.0?

https://www.polymer-project.org/2.0/docs/devguide/hybrid-elements

**Comment by Diwatt** [comment]
I want to upgrade it but i can tell you when. It depends on the development of one of our product.
I'm sure it will be before 2018 but if i can make it early be sure i'll try. Feel free to make a PR if you need it !

**Comment by warpech** [comment]
Implemented in https://github.com/display-interactive/pikaday-decorator/pull/4
